version: "3.9"
services:
    web:
        build:
            dockerfile: ./RoomService.WebAPI/Dockerfile
            context: .
        ports:
            - "8080:80"
        environment:
            - passwordKey=passwordKey123456789
    test:
        build:
            dockerfile: ./RoomService.Tests/Dockerfile
            context: .
        environment:
            - passwordKey=passwordKey123456789
